version: '3.9'
services:
  sv2-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.python-server
      args:
        - RUST_VERSION=1.82
    container_name: sv2-server
    ports:
      - "34254:34254"
    environment:
      - LD_LIBRARY_PATH=/usr/lib

  sv2-client-python:
    build:
      context: ..
      dockerfile: docker/Dockerfile.python-client
      args:
        - RUST_VERSION=1.82
    container_name: sv2-client-python
    environment:
      - LD_LIBRARY_PATH=/usr/lib
      - SV2_HOST=sv2-server
      - SV2_PORT=34254

  sv2-client-go:
    build:
      context: ..
      dockerfile: docker/Dockerfile.go-client
      args:
        - RUST_VERSION=1.82
    container_name: sv2-client-go
    environment:
      - LD_LIBRARY_PATH=/usr/lib
      - SV2_HOST=sv2-server
      - SV2_PORT=34254

  sv2-server-go:
    build:
      context: ..
      dockerfile: docker/Dockerfile.go-server
      args:
        - RUST_VERSION=1.82
    container_name: sv2-server-go
    ports:
      - "34254:34254"
    environment:
      - LD_LIBRARY_PATH=/usr/lib

networks:
  default:
    name: sv2-net
